#!/bin/bash
##################################################################################
##### LICENSE ####################################################################
##################################################################################
####                                                                          ####
#### Copyright (C) 2018 wuseman <info@sendit.nu>                              ####
####                                                                          ####
#### This program is free software: you can redistribute it and/or modify     ####
#### it under the terms of the GNU General Public License as published by     ####
#### the Free Software Foundation, either version 3 of the License, or        ####
#### (at your option) any later version.                                      ####
####                                                                          ####
#### This program is distributed in the hope that it will be useful,          ####
#### but WITHOUT ANY WARRANTY; without even the implied warranty of           ####
#### MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the            ####
#### GNU General Public License at <http://www.gnu.org/licenses/> for         ####
#### more details.                                                            ####
####                                                                          ####
##################################################################################
##### GREETINGS ##################################################################
##################################################################################
####                                                                          ####
#### To all developers that contributes to all kind of open source projects   ####
#### Keep up the good work!                                                   #<3#
####                                                                          ####
#### https://sendit.nu & https://github.com/wuseman                           ####
####                                                                          ####
##################################################################################
#### DESCRIPTION #################################################################
##################################################################################
####                                                                          ####
#### This is the tool you need run to get the release-archiver to begin       ####
#### to sort releases, we count how many times we need to run the loop with   ####
#### a simple wc -l command..                                                 ####
####                                                                          ####
#### Enjoy another awesome 'bash' script from wuseman. Questions? Conact me!  ####
####                                                                          ####
##################################################################################
#### Begin of code  ##############################################################
##################################################################################

############################################################################
#                                                                          #
# DO NOT TOUCH ANYTHING BELOW UNLESS YOU KNOW EXACTLY WHAT YOU ARE DOING,  #
# THERE MIGHT BE RISKS SINCE IT CAN ERASE UNWANTED DATA                    #
#                                                                          #
############################################################################
source ./warchiver.sh

# Needed for DEBUG only
# wait="sleep 10"
## define end value ##
END="$(ls $section | grep [A-Z] | awk -F'.' '{print $1}' | awk -F'_' '{print $1}' | sort | uniq | wc -l)"

## print date five times ##
x=$END
echo -e "\e[1;35m\e[0;1m----------------------------------------------------------------------------"
echo -e "# We will now begin to move folders into their archive path, please wait....                "
echo -e "----------------------------------------------------------------------------\e[0m\e[0m"
echo -e "\e[0;1m[+]\e[0m \e[1;32mRESORTING:\n\e[0m\e[0m\e[1;33m$(cat /tmp/all_releases | grep ^$(cat /tmp/releases))\e[0m \e[1;34 \e[0;1---->\e[0m \e[0m\e[1;32m$(pwd)/$(cat /tmp/create_dirs)\e[0m "

while [ $x -gt 0 ];
do
#    $wait
     sh warchiver # Let us tell warchiver to begin sort
done
echo -e "\n\n All releases has been succesfully transfered into their archive folders\n"
echo -e "- DONE ----------------------------------------------------------------------\n"


